defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  adapter: mongodb
  database: catchytune_development

test:
  <<: *defaults
  adapter: mongodb
  database: catchytune_test

production:
  adapter: mongodb
  uri: <%= ENV['MONGOHQ_URL'] %>
